In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [ ]:
from google.colab import files
uploaded =files.upload()

Saving Billing_Data.csv to Billing_Data.csv
Saving Patient_Data.csv to Patient_Data.csv

In [ ]:
pdf=pd.read_csv("Billing_Data.csv")
bdf=pd.read_csv("Patient_Data.csv")

In [ ]:
pdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
bdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [ ]:
pdf.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [ ]:
bdf.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [ ]:
pdf.isnull().sum()

PatientID           0
InsuranceCovered    0
FinalAmount         0
dtype: int64

In [ ]:
bdf.isnull().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        2
ReceptionistID    0
CheckInTime       0
dtype: int64

In [ ]:
pdf.duplicated().sum()

np.int64(0)

In [ ]:
bdf.duplicated().sum()

np.int64(1)


2. Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount']

In [ ]:
bdf.columns

Index(['PatientID', 'Name', 'Department', 'Doctor', 'BillAmount',
       'ReceptionistID', 'CheckInTime'],
      dtype='object')

In [ ]:
# Select relevant columns for billing
billing_relevant=bdf[['PatientID', 'Department', 'Doctor', 'BillAmount']]

In [ ]:
#show the result
print("Relevant billing columns: \n")
billing_relevant.head()

Relevant billing columns:

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN


3. Drop administrative columns like ['ReceptionistID', 'CheckInTime']

In [ ]:
bdf.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [ ]:
bdf=bdf.drop(columns=['ReceptionistID', 'CheckInTime'], errors='ignore')

In [ ]:
#after droppin the adminstrative columns
bdf.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

4. Use groupby to find total bill amount per department

In [ ]:
dept_bill_summary=billing_relevant.groupby('Department')['BillAmount'].sum().reset_index()

In [ ]:
dept_bill_summary
#total bill amount per department

    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

5. Remove duplicate patient records based on PatientID

In [ ]:
bdf.duplicated().sum()

np.int64(1)

In [ ]:
#remove duplicate patient records based on patientID
patient_unique = bdf.drop_duplicates(subset=['PatientID'],inplace=True)

In [ ]:
# After removing duplicate PatientID records
patient_unique.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [ ]:
bdf.duplicated().sum()

np.int64(0)


6. Fill missing BillAmount values with the mean bill amount

In [ ]:
# Fill missing BillAmount values with the mean bill amount
mean_bill=patient_unique['BillAmount'].mean()

patient_unique['BillAmount'].fillna(mean_bill,inplace=True)

In [ ]:
patient_unique

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [ ]:
patient_unique.isnull().sum()

PatientID     0
Name          0
Department    0
Doctor        0
BillAmount    0
dtype: int64

7. Merge the billing dataset with patient dataset on PatientID

In [64]:
merge_df=pd.merge(left=bdf,right=pdf,how='inner',on='PatientID')

In [66]:
merge_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000,3000
1,102,Bob,Neurology,Dr. John,NaN,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3000,3200
4,105,Eva,Dermatology,Dr. Rose,NaN,1000,4000

8. Concatenate an additional DataFrame that contains new patients for the current week (row-wise)

In [67]:
# Concatenate new patients (row-wise)
new_patients = pd.DataFrame({
    'PatientID':[107,108],
    'Name':['Martin','lewis'],
    'Department':['oncology','cardiology'],
    'Doctor':['Dr.Ashwin','Dr.Piyush'],
    'BillAmount':[9000,6500],
    'InsuranceCovered':[3000,2500],
    'FinalAmount':[5000,3500]

})

In [71]:
# Concatenate with existing merged data
full_patientdf=pd.concat([bdf,new_patients],ignore_index=True)

In [72]:
full_patientdf

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,NaN,NaN
1,102,Bob,Neurology,Dr. John,NaN,NaN,NaN
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,NaN,NaN
3,104,David,Cardiology,Dr. Smith,6200.0,NaN,NaN
4,105,Eva,Dermatology,Dr. Rose,NaN,NaN,NaN
5,107,Martin,oncology,Dr.Ashwin,9000.0,3000.0,5000.0
6,108,lewis,cardiology,Dr.Piyush,6500.0,2500.0,3500.0

9. Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise)

In [83]:
# new billing column
new_billing_column=pd.DataFrame({
    'InsuranceCovered':[3000,2000,1000,5000,4000,2500,None,None],
    'FinalAmount':[5000,3000,1000,6000,5500,3500,None,None]
})

In [93]:
# Concatenate new billing category (column-wise)
final_df = pd.concat([merge_df.reset_index(drop=True), new_billing_column], axis=1)
merge_df['FinalAmount'] = merge_df['BillAmount'] - merge_df['InsuranceCovered']

In [94]:
#Final Cleaned Patient Billing Dataset:
final_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount
0,101.0,Alice,Cardiology,Dr. Smith,5000.0,2000.0,3000.0,3000.0,5000.0
1,102.0,Bob,Neurology,Dr. John,NaN,1500.0,NaN,2000.0,3000.0
2,103.0,Charlie,Orthopedics,Dr. Lee,7500.0,2500.0,5000.0,1000.0,1000.0
3,104.0,David,Cardiology,Dr. Smith,6200.0,3000.0,3200.0,5000.0,6000.0
4,105.0,Eva,Dermatology,Dr. Rose,NaN,1000.0,NaN,4000.0,5500.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2500.0,3500.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN